name: Create Secure Webhook JSON

on: [push]

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Create secure webhook.json
        run: |
          mkdir -p docs
          echo '{"webhook": "${{ secrets.DISC_WEB_HOOK }}"}' > docs/secure-webhook.json
      - name: Commit file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/secure-webhook.json
          git commit -m "Add secure webhook json"
          git push
